---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-git

inputs:
  - name: git-repo
  - name: blue-green-file

outputs:
  - name: blue-green-output
run:
  path: git-repo/ci/tasks/restart-artifactory.sh

params:
  GIT_REPO:
  PASSWORD:
  ARTIFACTORY_COLOR_FILENAME:
